### ISSUE TITLE
Issues getting the project running

### ISSUE THREAD

**Issue by francotiveron** [panesofglass/trail#13]
W10
Microsoft Visual Studio Community 2017 Preview
Version 15.7.0 Preview 5.0
VisualStudio.15.Preview/15.7.0-pre.5.0+27625.0
Microsoft .NET Framework
Version 4.7.02558

1. Clone repository -> ok
2. VS restore fails looking for non-existent <basedir>\bin directory
3. dotnet restore fails with the same error
4. manually create <basedir>\bin directory
5. dotnet restore succeeds (<basedir>\bin directory remain empty though)
6. dotnet build and VS build succeeds
7. VS run seems to start but exits straightaway without indication
8. dotnet run --project sample/standalone/BlazorApp1 fails with the following error

Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj

9. changed attributes to directory C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps (make it full control for everyone) -> both dotnet run and VS run fail with a .NET exception complaining both Debug and Release folder are present

10. removed Release manually -> bot run commands succeed, IE browser starts and shows "Loading...", but nothing else happens, it remains stuck there.

11. run in Edge -> after 6 seconds the app finally runs as expected

**Comment by panesofglass** [comment]
The best way to do an initial build is to run `build.cmd`. In order to get the packaging working, I set my bin folder as a local nuget repository that's required to build the `Trail.BlazorRedux` library. That's probably what you are running up against. The `build.cmd` should get that all set up for you. If you have any ideas as to how to get this to work easier direct from VS, I'd be happy to update the setup.

**Comment by francotiveron** [comment]
Thanks for your answer. I'll give it a go. It's still at an early stage I guess.

**Comment by panesofglass** [comment]
Yes, it's still very early. I need to add some additional feature support, as well.
