### ISSUE TITLE
Proposal: shift contributions to Bolero

### ISSUE THREAD

**Issue by panesofglass** [panesofglass/trail#22]
@IntelliFactory has created a new repository with equivalent and greater goals (and implementation) at https://github.com/fsbolero/Bolero. I suggest and would like to focus future efforts as contributions to that repository.

cc @granicz @Tarmil

**Comment by granicz** [comment]
@panesofglass Thanks very much! Looking forward to working with you on [Bolero](https://github.com/fsbolero/Bolero).
